extent:
  min_lon: 142.858
  min_lat: 43.669
  max_lon: 142.862
  max_lat: 43.671

zoom: 14

outputs:
  - type: kmz
    path: output/test-tiles.kmz
    web_compatible: false

layers:
  - name: std
    opacity: 100
    blend_mode: normal
